project:
  type: website

website:
  title: "Andrew Yule"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: "Posts" 
      - href: About.qmd
        text: "About"
      - href: Contact.qmd
        text: "Contact"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ayule89/
      - icon: twitter
        href: https://twitter.com/ayule89
      - icon: github
        href: https://github.com/ayule89
format:
  html:
    theme: litera
    css: styles.css
    mainfont: "Source Sans Pro"
    
