project:
  type: website

website:
  title: "Andrew Yule"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: "Posts" 
      - About.qmd
      - Contact.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ayule89/
      - icon: twitter
        href: https://twitter.com/ayule89
      - icon: github
        href: https://github.com/ayule89
format:
  html:
    theme: litera
    css: styles.css



